export const EmployeeUserBasicDetailsAttributes = {
    title: "",
    initials: "",
    first_name: "",
    middle_name: "",
    last_name: "",
    nickname: "",
    date_of_birth: "",
    place_of_birth: "",
    gender: "",
    marital_status: "",
    blood_type: "",
    citizenship: "",
    photo: "",
};
